/**
 * AUTO-GENERATED — DO NOT EDIT
 * 
 * Generated by: bun run scripts/sync-block-schema.ts
 * Source of truth: src/lib/block-reference.ts
 * 
 * Re-run after adding or modifying block types.
 */

export const BLOCK_CREATION_TOOLS = [
  {
    "type": "function",
    "function": {
      "name": "create_hero_block",
      "description": "Create a Hero section: Large banner section with title, subtitle, call-to-action buttons. Supports images, direct video, YouTube, and Vimeo backgrounds.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Main headline",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text below the title",
            "type": "string"
          },
          "eyebrow": {
            "description": "Small uppercase label above the title, e.g. \"NEW\", \"SINCE 1998\"",
            "type": "string"
          },
          "eyebrowColor": {
            "description": "Eyebrow tint",
            "type": "string",
            "enum": [
              "default",
              "primary",
              "muted"
            ]
          },
          "layout": {
            "description": "Hero composition: centered content, or content beside the image",
            "type": "string",
            "enum": [
              "centered",
              "split-left",
              "split-right"
            ]
          },
          "backgroundType": {
            "description": "Background style; \"none\" leaves the section transparent",
            "type": "string",
            "enum": [
              "color",
              "image",
              "video",
              "none"
            ]
          },
          "backgroundImage": {
            "description": "Background image URL — this is the field the renderer reads",
            "type": "string"
          },
          "imageSrc": {
            "description": "Legacy: earlier name for the background image URL; prefer backgroundImage",
            "type": "string"
          },
          "videoUrl": {
            "description": "Background video URL or YouTube/Vimeo URL (when backgroundType is \"video\")",
            "type": "string"
          },
          "videoUrlWebm": {
            "description": "Optional WebM source added alongside videoUrl for browsers that prefer it",
            "type": "string"
          },
          "videoType": {
            "description": "Video source type",
            "type": "string",
            "enum": [
              "direct",
              "youtube",
              "vimeo"
            ]
          },
          "videoPosterUrl": {
            "description": "Poster image shown before the video plays, and the fallback on mobile",
            "type": "string"
          },
          "videoAutoplay": {
            "description": "Start the background video automatically",
            "type": "boolean"
          },
          "videoLoop": {
            "description": "Loop the background video",
            "type": "boolean"
          },
          "videoMuted": {
            "description": "Start the video muted (required for autoplay in most browsers)",
            "type": "boolean"
          },
          "showVideoControls": {
            "description": "Show play/pause/mute controls for video",
            "type": "boolean"
          },
          "heightMode": {
            "description": "Section height",
            "type": "string",
            "enum": [
              "viewport",
              "80vh",
              "70vh",
              "60vh",
              "50vh",
              "auto"
            ]
          },
          "contentAlignment": {
            "description": "Vertical position of the content block",
            "type": "string",
            "enum": [
              "top",
              "center",
              "bottom"
            ]
          },
          "textAlignment": {
            "description": "Text alignment",
            "type": "string",
            "enum": [
              "left",
              "center",
              "right"
            ]
          },
          "textTheme": {
            "description": "Text color scheme; \"auto\" derives it from the overlay",
            "type": "string",
            "enum": [
              "auto",
              "light",
              "dark"
            ]
          },
          "overlayOpacity": {
            "description": "Overlay opacity over image/video, 0-100",
            "type": "number"
          },
          "overlayColor": {
            "description": "Overlay color style",
            "type": "string",
            "enum": [
              "dark",
              "light",
              "primary"
            ]
          },
          "parallaxEffect": {
            "description": "Background drifts slower than the page (transform-based parallax — works on iOS, unlike background-attachment: fixed)",
            "type": "boolean"
          },
          "titleSize": {
            "description": "Title scale",
            "type": "string",
            "enum": [
              "default",
              "large",
              "display",
              "massive"
            ]
          },
          "gradientTitle": {
            "description": "Render the title with the brand gradient fill",
            "type": "boolean"
          },
          "titleAnimation": {
            "description": "Title entrance animation",
            "type": "string",
            "enum": [
              "none",
              "fade-in",
              "slide-up",
              "typewriter"
            ]
          },
          "subtitleAnimation": {
            "description": "Subtitle entrance animation, delayed after the title",
            "type": "string",
            "enum": [
              "none",
              "fade-in",
              "slide-up"
            ]
          },
          "showScrollIndicator": {
            "description": "Show scroll down arrow",
            "type": "boolean"
          },
          "primaryButton": {
            "description": "Primary CTA button { text, url }",
            "type": "object"
          },
          "secondaryButton": {
            "description": "Secondary button { text, url }",
            "type": "object"
          },
          "heroStats": {
            "description": "Proof numbers rendered in a row under the CTA, e.g. \"500+ customers\"",
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "title"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_text_block",
      "description": "Create a Text section: Rich text content block for paragraphs, headings, lists, and formatted text.",
      "parameters": {
        "type": "object",
        "properties": {
          "eyebrow": {
            "description": "Small uppercase label above the display title, e.g. \"SERVICES\"",
            "type": "string"
          },
          "eyebrowColor": {
            "description": "Eyebrow color as a CSS/hex value; defaults to brand primary",
            "type": "string"
          },
          "title": {
            "description": "Optional display heading above the rich text",
            "type": "string"
          },
          "titleSize": {
            "description": "Title scale",
            "type": "string",
            "enum": [
              "default",
              "large",
              "display"
            ]
          },
          "accentText": {
            "description": "Script-font accent word/phrase paired with the title, e.g. \"Excellence\"",
            "type": "string"
          },
          "accentPosition": {
            "description": "Where the accent renders relative to the title",
            "type": "string",
            "enum": [
              "start",
              "end",
              "inline"
            ]
          },
          "content": {
            "description": "Rich text content in Tiptap format (Tiptap JSON: {\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"...\"}]}]})",
            "type": "object"
          },
          "alignment": {
            "description": "Text alignment",
            "type": "string",
            "enum": [
              "left",
              "center",
              "right"
            ]
          },
          "maxWidth": {
            "description": "Content width",
            "type": "string",
            "enum": [
              "prose",
              "full"
            ]
          },
          "backgroundColor": {
            "description": "Section background color override (CSS color)",
            "type": "string"
          }
        },
        "required": [
          "content"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_quote_block",
      "description": "Create a Quote section: Highlighted quotation with optional attribution.",
      "parameters": {
        "type": "object",
        "properties": {
          "text": {
            "description": "The quote text — this is the field the renderer reads",
            "type": "string"
          },
          "quote": {
            "description": "Legacy: earlier name for the quote text; prefer text",
            "type": "string"
          },
          "author": {
            "description": "Quote author name",
            "type": "string"
          },
          "source": {
            "description": "Where the quote comes from, e.g. a book, article or company",
            "type": "string"
          },
          "role": {
            "description": "Legacy: author role or title; not rendered",
            "type": "string"
          },
          "variant": {
            "description": "Visual style: plain left-rule quote, or a decorative tinted card",
            "type": "string",
            "enum": [
              "simple",
              "styled"
            ]
          }
        },
        "required": [
          "text"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_cta_block",
      "description": "Create a Call to Action section: Prominent section encouraging users to take action.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "CTA headline",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text",
            "type": "string"
          },
          "buttonText": {
            "description": "Primary button label",
            "type": "string"
          },
          "buttonUrl": {
            "description": "Primary button link URL",
            "type": "string"
          },
          "secondaryButtonText": {
            "description": "Secondary button label",
            "type": "string"
          },
          "secondaryButtonUrl": {
            "description": "Secondary button link URL",
            "type": "string"
          },
          "variant": {
            "description": "Layout style: solid/gradient panel, full background image, split image+content, or understated",
            "type": "string",
            "enum": [
              "default",
              "with-image",
              "split",
              "minimal"
            ]
          },
          "backgroundImage": {
            "description": "Background image URL (used by the \"with-image\" and \"split\" variants)",
            "type": "string"
          },
          "overlayOpacity": {
            "description": "Darkening overlay over the background image, 0-1",
            "type": "number"
          },
          "gradient": {
            "description": "Use gradient background",
            "type": "boolean"
          }
        },
        "required": [
          "title",
          "buttonText",
          "buttonUrl"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_features_block",
      "description": "Create a Features section: Grid of feature cards with icons, titles, and descriptions.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text under the title",
            "type": "string"
          },
          "features": {
            "description": "Array of features [{ id, icon, title, description, link }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          },
          "layout": {
            "description": "Grid of cards or a stacked list",
            "type": "string",
            "enum": [
              "grid",
              "list"
            ]
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "cards",
              "minimal",
              "centered"
            ]
          },
          "iconStyle": {
            "description": "Icon background shape",
            "type": "string",
            "enum": [
              "circle",
              "square",
              "none"
            ]
          },
          "showLinks": {
            "description": "Render each feature's link as a \"Read more\" action",
            "type": "boolean"
          },
          "hoverEffect": {
            "description": "Effect on card hover",
            "type": "string",
            "enum": [
              "none",
              "lift",
              "glow",
              "border"
            ]
          },
          "cardStyle": {
            "description": "Card surface treatment",
            "type": "string",
            "enum": [
              "default",
              "glass",
              "gradient-border"
            ]
          },
          "staggeredReveal": {
            "description": "Animate the cards in one by one as they enter the viewport",
            "type": "boolean"
          }
        },
        "required": [
          "features"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_stats_block",
      "description": "Create a Statistics section: Display key metrics and numbers.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "stats": {
            "description": "Array of stats [{ value, label }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "animated": {
            "description": "Animate the numbers when they scroll into view",
            "type": "boolean"
          },
          "animationStyle": {
            "description": "How each number appears",
            "type": "string",
            "enum": [
              "count-up",
              "fade-in",
              "slide-up",
              "typewriter"
            ]
          },
          "animationDuration": {
            "description": "Animation length in ms — 1000 fast, 2000 normal, 3000 slow",
            "type": "number"
          }
        },
        "required": [
          "stats"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_testimonials_block",
      "description": "Create a Testimonials section: Customer quotes and reviews.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "testimonials": {
            "description": "Array of testimonials [{ id, content, author, role, company, rating, avatar }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "layout": {
            "description": "Display layout",
            "type": "string",
            "enum": [
              "carousel",
              "grid"
            ]
          },
          "columns": {
            "description": "Grid columns (when layout is grid)",
            "type": "number"
          },
          "showRating": {
            "description": "Show star ratings",
            "type": "boolean"
          },
          "showAvatar": {
            "description": "Show author avatars",
            "type": "boolean"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "cards",
              "minimal",
              "bubbles"
            ]
          },
          "autoplay": {
            "description": "Auto-rotate carousel",
            "type": "boolean"
          },
          "autoplaySpeed": {
            "description": "Seconds between slides",
            "type": "number"
          },
          "subtitle": {
            "description": "Supporting text under the title",
            "type": "string"
          }
        },
        "required": [
          "testimonials"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_team_block",
      "description": "Create a Team section: Team member grid with photos and bios.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text under the title",
            "type": "string"
          },
          "members": {
            "description": "Array of members [{ id, name, role, bio, image, linkedin, twitter }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          },
          "layout": {
            "description": "Grid of cards or a swipeable carousel",
            "type": "string",
            "enum": [
              "grid",
              "carousel"
            ]
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "cards",
              "minimal"
            ]
          },
          "showRole": {
            "description": "Show member roles",
            "type": "boolean"
          },
          "showBio": {
            "description": "Show member bios",
            "type": "boolean"
          },
          "showSocial": {
            "description": "Show each member's social links",
            "type": "boolean"
          },
          "staggeredReveal": {
            "description": "Animate the members in one by one as they enter the viewport",
            "type": "boolean"
          }
        },
        "required": [
          "members"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_logos_block",
      "description": "Create a Logos section: Partner or client logo showcase.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text under the title",
            "type": "string"
          },
          "logos": {
            "description": "Array of logos [{ id, name, logo }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          },
          "layout": {
            "description": "Display layout",
            "type": "string",
            "enum": [
              "grid",
              "carousel",
              "scroll"
            ]
          },
          "variant": {
            "description": "Color treatment",
            "type": "string",
            "enum": [
              "grayscale",
              "color",
              "default"
            ]
          },
          "logoSize": {
            "description": "Logo size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "autoplay": {
            "description": "Auto-advance the carousel layout",
            "type": "boolean"
          },
          "autoplaySpeed": {
            "description": "Seconds between carousel slides",
            "type": "number"
          }
        },
        "required": [
          "logos"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_timeline_block",
      "description": "Create a Timeline section: Step-by-step or chronological content.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "steps": {
            "description": "Array of steps [{ id, icon, title, description, date }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Layout style",
            "type": "string",
            "enum": [
              "horizontal",
              "vertical",
              "alternating"
            ]
          },
          "showDates": {
            "description": "Show date/step labels",
            "type": "boolean"
          },
          "staggeredReveal": {
            "description": "Animate the entries in one by one as they enter the viewport",
            "type": "boolean"
          }
        },
        "required": [
          "steps"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_accordion_block",
      "description": "Create a Accordion section: Expandable FAQ or content sections.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "items": {
            "description": "FAQ items",
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "items"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_image_block",
      "description": "Create a Image section: Single image with optional caption.",
      "parameters": {
        "type": "object",
        "properties": {
          "src": {
            "description": "Image URL",
            "type": "string"
          },
          "alt": {
            "description": "Alt text for accessibility",
            "type": "string"
          },
          "caption": {
            "description": "Caption below the image (hidden when overlayText is set)",
            "type": "string"
          },
          "aspectRatio": {
            "description": "Image aspect ratio",
            "type": "string",
            "enum": [
              "auto",
              "16:9",
              "4:3",
              "1:1",
              "21:9"
            ]
          },
          "size": {
            "description": "Image width",
            "type": "string",
            "enum": [
              "small",
              "medium",
              "large",
              "full"
            ]
          },
          "fullBleed": {
            "description": "Break out of the container and run edge to edge",
            "type": "boolean"
          },
          "rounded": {
            "description": "Rounded corners",
            "type": "boolean"
          },
          "shadow": {
            "description": "Drop shadow depth",
            "type": "string",
            "enum": [
              "none",
              "sm",
              "md",
              "lg"
            ]
          },
          "hoverEffect": {
            "description": "Effect on hover",
            "type": "string",
            "enum": [
              "none",
              "zoom",
              "fade",
              "lift"
            ]
          },
          "overlayText": {
            "description": "Text rendered on top of the image instead of a caption",
            "type": "string"
          },
          "overlayPosition": {
            "description": "Where the overlay text sits",
            "type": "string",
            "enum": [
              "center",
              "bottom-left",
              "bottom-center"
            ]
          }
        },
        "required": [
          "src",
          "alt"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_gallery_block",
      "description": "Create a Gallery section: Grid of images.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "images": {
            "description": "Array of images [{ id, src, alt, caption }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "layout": {
            "description": "Presentation: even grid, swipeable carousel, or masonry with varying heights",
            "type": "string",
            "enum": [
              "grid",
              "carousel",
              "masonry"
            ]
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          },
          "gap": {
            "description": "Spacing between images",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          }
        },
        "required": [
          "images"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_youtube_block",
      "description": "Create a YouTube section: Embedded YouTube video.",
      "parameters": {
        "type": "object",
        "properties": {
          "url": {
            "description": "YouTube watch, youtu.be, embed URL or a bare 11-character video ID — this is the field the renderer reads",
            "type": "string"
          },
          "videoId": {
            "description": "Legacy: bare video ID; prefer url, which also accepts an ID",
            "type": "string"
          },
          "title": {
            "description": "Video title, used as the iframe title and as a caption under the player",
            "type": "string"
          },
          "autoplay": {
            "description": "Start the video automatically (browsers require mute for this to work)",
            "type": "boolean"
          },
          "loop": {
            "description": "Repeat the video when it ends",
            "type": "boolean"
          },
          "mute": {
            "description": "Start without sound",
            "type": "boolean"
          },
          "controls": {
            "description": "Show the YouTube play/pause controls",
            "type": "boolean"
          },
          "aspectRatio": {
            "description": "Video aspect ratio",
            "type": "string",
            "enum": [
              "16:9",
              "4:3"
            ]
          }
        },
        "required": [
          "url"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_two_column_block",
      "description": "Create a Two Column section: Side-by-side content and image layout with editorial styling: eyebrow label, display-size title, script-font accent text, CTA and rich image controls.",
      "parameters": {
        "type": "object",
        "properties": {
          "eyebrow": {
            "description": "Small uppercase label above the title, e.g. \"ABOUT US\", \"SERVICES\"",
            "type": "string"
          },
          "eyebrowColor": {
            "description": "Eyebrow color; defaults to brand primary",
            "type": "string"
          },
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "titleSize": {
            "description": "Title scale",
            "type": "string",
            "enum": [
              "default",
              "large",
              "display"
            ]
          },
          "accentText": {
            "description": "Script-font accent word/phrase, e.g. \"Excellence\" — pairs with the title",
            "type": "string"
          },
          "accentPosition": {
            "description": "Where the accent renders relative to the title",
            "type": "string",
            "enum": [
              "start",
              "end",
              "inline"
            ]
          },
          "content": {
            "description": "Rich text content (Tiptap JSON: {\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"...\"}]}]})",
            "type": "object"
          },
          "ctaText": {
            "description": "Call-to-action button label",
            "type": "string"
          },
          "ctaUrl": {
            "description": "Call-to-action link",
            "type": "string"
          },
          "note": {
            "description": "Small print under the CTA",
            "type": "string"
          },
          "imageSrc": {
            "description": "Image URL",
            "type": "string"
          },
          "imageAlt": {
            "description": "Image alt text",
            "type": "string"
          },
          "imagePosition": {
            "description": "Image placement",
            "type": "string",
            "enum": [
              "left",
              "right"
            ]
          },
          "imageAspect": {
            "description": "Aspect ratio",
            "type": "string",
            "enum": [
              "auto",
              "1:1",
              "4:3",
              "3:2",
              "16:9",
              "21:9"
            ]
          },
          "imageFit": {
            "description": "Fill & crop vs show all",
            "type": "string",
            "enum": [
              "cover",
              "contain"
            ]
          },
          "imageRounded": {
            "description": "Corner radius",
            "type": "string",
            "enum": [
              "none",
              "sm",
              "md",
              "lg",
              "xl",
              "full"
            ]
          },
          "secondImageSrc": {
            "description": "Optional second, offset image for a collage feel",
            "type": "string"
          },
          "secondImageAlt": {
            "description": "Second image alt text",
            "type": "string"
          },
          "stickyColumn": {
            "description": "Column that stays pinned while the other scrolls",
            "type": "string",
            "enum": [
              "none",
              "image",
              "text"
            ]
          },
          "backgroundColor": {
            "description": "Section background override",
            "type": "string"
          },
          "layout": {
            "description": "Column split, or two-text-column mode instead of text+image",
            "type": "string",
            "enum": [
              "50-50",
              "60-40",
              "40-60",
              "text-text"
            ]
          },
          "leftColumn": {
            "description": "Two-text mode: left column content (Tiptap JSON: {\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"...\"}]}]})",
            "type": "object"
          },
          "rightColumn": {
            "description": "Two-text mode: right column content (Tiptap JSON: {\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"...\"}]}]})",
            "type": "object"
          },
          "secondaryContent": {
            "description": "Two-text mode (layout 'text-text'): right column content, paired with content as the left column (Tiptap JSON: {\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"...\"}]}]})",
            "type": "object"
          },
          "primaryButton": {
            "description": "CTA as an object ({ text, url }) — alternative to ctaText/ctaUrl",
            "type": "object"
          }
        },
        "required": [
          "content"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_separator_block",
      "description": "Create a Separator section: Visual divider between sections.",
      "parameters": {
        "type": "object",
        "properties": {
          "style": {
            "description": "Divider style",
            "type": "string",
            "enum": [
              "line",
              "dots",
              "gradient",
              "none"
            ]
          },
          "spacing": {
            "description": "Vertical spacing",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_info_box_block",
      "description": "Create a Info Box section: Highlighted information box (tip, warning, etc.).",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Box title",
            "type": "string"
          },
          "content": {
            "description": "Box content (Tiptap JSON: {\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"...\"}]}]})",
            "type": "object"
          },
          "variant": {
            "description": "Box style",
            "type": "string",
            "enum": [
              "info",
              "warning",
              "success",
              "error"
            ]
          }
        },
        "required": [
          "title"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_link_grid_block",
      "description": "Create a Link Grid section: Grid of linked cards.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "links": {
            "description": "Array of links [{ id, title, description, url, icon }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          }
        },
        "required": [
          "links"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_form_block",
      "description": "Create a Form section: Contact or data collection form.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Form title",
            "type": "string"
          },
          "description": {
            "description": "Text under the title explaining what the form is for",
            "type": "string"
          },
          "fields": {
            "description": "Array of fields [{ id, type, label, required, placeholder, width, options }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "submitButtonText": {
            "description": "Submit button label",
            "type": "string"
          },
          "successMessage": {
            "description": "Message shown after submission",
            "type": "string"
          },
          "notifyEmail": {
            "description": "Address that receives an email on every submission",
            "type": "string"
          },
          "jobPostingId": {
            "description": "Bind submissions to a job posting — turns the form into a job application",
            "type": "string"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "card",
              "minimal"
            ]
          }
        },
        "required": [
          "fields"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_chat_block",
      "description": "Create a Chat section: Embedded AI chat interface.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Chat title",
            "type": "string"
          },
          "height": {
            "description": "Chat height",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "variant": {
            "description": "Display style",
            "type": "string",
            "enum": [
              "embedded",
              "card",
              "floating"
            ]
          },
          "showSidebar": {
            "description": "Show conversation sidebar",
            "type": "boolean"
          },
          "initialPrompt": {
            "description": "Initial bot message",
            "type": "string"
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_newsletter_block",
      "description": "Create a Newsletter section: Email signup form.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "description": {
            "description": "Description text",
            "type": "string"
          },
          "buttonText": {
            "description": "Submit button label",
            "type": "string"
          },
          "successMessage": {
            "description": "Success message",
            "type": "string"
          },
          "emailPlaceholder": {
            "description": "Email field placeholder — set it in the site's own language",
            "type": "string"
          },
          "namePlaceholder": {
            "description": "Name field placeholder (only rendered when showNameField is on)",
            "type": "string"
          },
          "variant": {
            "description": "Visual style",
            "type": "string"
          },
          "showNameField": {
            "description": "Also ask for a name",
            "type": "boolean"
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_map_block",
      "description": "Create a Map section: Embedded Google Maps.",
      "parameters": {
        "type": "object",
        "properties": {
          "address": {
            "description": "Location address used to build the map URL",
            "type": "string"
          },
          "locationName": {
            "description": "Place name shown under the map, e.g. \"Main Office\"",
            "type": "string"
          },
          "title": {
            "description": "Heading above the map, e.g. \"Find Us\"",
            "type": "string"
          },
          "description": {
            "description": "Intro text under the heading",
            "type": "string"
          },
          "zoom": {
            "description": "Map zoom level",
            "type": "number"
          },
          "height": {
            "description": "Map height preset",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg",
              "xl"
            ]
          },
          "mapType": {
            "description": "Map tiles",
            "type": "string",
            "enum": [
              "roadmap",
              "satellite"
            ]
          },
          "showMarker": {
            "description": "Show location marker",
            "type": "boolean"
          },
          "showBorder": {
            "description": "Draw a border around the map frame",
            "type": "boolean"
          },
          "rounded": {
            "description": "Rounded map corners",
            "type": "boolean"
          },
          "loadOnConsent": {
            "description": "GDPR: do not load Google Maps until the visitor clicks to accept",
            "type": "boolean"
          }
        },
        "required": [
          "address"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_booking_block",
      "description": "Create a Booking section: Appointment booking form.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "description": {
            "description": "Description text",
            "type": "string"
          },
          "mode": {
            "description": "How visitors book: embedded external calendar, a request form, or the built-in Booking module flow",
            "type": "string",
            "enum": [
              "embed",
              "form",
              "smart"
            ]
          },
          "provider": {
            "description": "External calendar provider (mode \"embed\")",
            "type": "string",
            "enum": [
              "calendly",
              "cal",
              "hubspot",
              "custom"
            ]
          },
          "embedUrl": {
            "description": "Calendar URL or custom embed URL (mode \"embed\")",
            "type": "string"
          },
          "height": {
            "description": "Embed height: sm 400px, md 550px, lg 700px, xl 850px",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg",
              "xl"
            ]
          },
          "submitButtonText": {
            "description": "Submit button label",
            "type": "string"
          },
          "successMessage": {
            "description": "Success message",
            "type": "string"
          },
          "showPhoneField": {
            "description": "Include phone field",
            "type": "boolean"
          },
          "showDatePicker": {
            "description": "Include date preference field",
            "type": "boolean"
          },
          "showServiceSelector": {
            "description": "Let the visitor pick a service before booking",
            "type": "boolean"
          },
          "services": {
            "description": "Selectable services (mode \"form\" with showServiceSelector)",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "triggerWebhook": {
            "description": "Fire the booking automation webhook on submit",
            "type": "boolean"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "card",
              "minimal"
            ]
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_popup_block",
      "description": "Create a Popup section: Modal popup with content.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Popup heading",
            "type": "string"
          },
          "content": {
            "description": "Popup content (Tiptap JSON: {\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"...\"}]}]})",
            "type": "object"
          },
          "image": {
            "description": "Image shown above the content",
            "type": "string"
          },
          "buttonText": {
            "description": "Primary button label",
            "type": "string"
          },
          "buttonUrl": {
            "description": "Primary button link",
            "type": "string"
          },
          "secondaryButtonText": {
            "description": "Dismiss-style secondary button label, e.g. \"No thanks\"",
            "type": "string"
          },
          "trigger": {
            "description": "What opens the popup",
            "type": "string",
            "enum": [
              "time",
              "scroll",
              "exit-intent"
            ]
          },
          "delaySeconds": {
            "description": "Seconds before opening (trigger \"time\")",
            "type": "number"
          },
          "scrollPercentage": {
            "description": "Scroll depth in percent that opens it (trigger \"scroll\")",
            "type": "number"
          },
          "showOnce": {
            "description": "Do not show again after it has been dismissed",
            "type": "boolean"
          },
          "cookieDays": {
            "description": "How many days a dismissal is remembered",
            "type": "number"
          },
          "size": {
            "description": "Popup width",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "position": {
            "description": "Where it appears",
            "type": "string",
            "enum": [
              "center",
              "bottom-right",
              "bottom-left"
            ]
          },
          "overlayDark": {
            "description": "Dim and blur the page behind it (centered position only)",
            "type": "boolean"
          },
          "delay": {
            "description": "Legacy: earlier name for delaySeconds",
            "type": "number"
          }
        },
        "required": [
          "content"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_pricing_block",
      "description": "Create a Pricing section: Pricing tier cards.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text under the title",
            "type": "string"
          },
          "tiers": {
            "description": "Array of pricing tiers",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "productType": {
            "description": "When pricing is driven by the Products module, which product types to include",
            "type": "string",
            "enum": [
              "all",
              "recurring",
              "one_time"
            ]
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "cards",
              "compact"
            ]
          }
        },
        "required": [
          "tiers"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_comparison_block",
      "description": "Create a Comparison section: Feature comparison table.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text under the title",
            "type": "string"
          },
          "products": {
            "description": "Products to compare [{ id, name, highlighted }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "features": {
            "description": "Features to compare [{ id, name, values[] }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Table style",
            "type": "string",
            "enum": [
              "striped",
              "bordered"
            ]
          },
          "showPrices": {
            "description": "Show prices in header",
            "type": "boolean"
          },
          "showButtons": {
            "description": "Show CTA buttons",
            "type": "boolean"
          },
          "stickyHeader": {
            "description": "Keep the product header row pinned while the table scrolls",
            "type": "boolean"
          }
        },
        "required": [
          "products",
          "features"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_trust_bar_block",
      "description": "Create a Trust Bar section: Horizontal bar with trust signals like free shipping, returns policy, secure payment.",
      "parameters": {
        "type": "object",
        "properties": {
          "items": {
            "description": "Array of { icon, text } items. Icons: truck, rotate-ccw, shield-check, credit-card, clock, star, heart-handshake, award, leaf, zap, globe, lock",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "bordered",
              "filled"
            ]
          },
          "size": {
            "description": "Size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_category_nav_block",
      "description": "Create a Category Navigation section: Visual tiles linking to product categories with images and names.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "columns": {
            "description": "Grid columns",
            "type": "number"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "cards",
              "minimal",
              "overlay"
            ]
          },
          "showDescription": {
            "description": "Show category descriptions",
            "type": "boolean"
          },
          "linkBase": {
            "description": "Base URL path",
            "type": "string"
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_shipping_info_block",
      "description": "Create a Shipping Info section: Shipping, delivery, and returns information block.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "items": {
            "description": "Array of { icon, title, description } items",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Layout variant",
            "type": "string",
            "enum": [
              "list",
              "grid",
              "compact"
            ]
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_article_grid_block",
      "description": "Create a Article Grid section: Blog post or article grid.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          },
          "articles": {
            "description": "Manually curated cards — this block does not read the blog; use latest-posts for that",
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "articles"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_latest_posts_block",
      "description": "Create a Latest Posts section: Auto-pulls the most recent published blog posts.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "count": {
            "description": "Posts to show (1-6)",
            "type": "number"
          },
          "columns": {
            "description": "Columns (1-4)",
            "type": "number"
          },
          "category": {
            "description": "Filter by category",
            "type": "string"
          },
          "showExcerpt": {
            "description": "Show post excerpt",
            "type": "boolean"
          },
          "showDate": {
            "description": "Show published date",
            "type": "boolean"
          },
          "ctaText": {
            "description": "CTA text",
            "type": "string"
          },
          "ctaUrl": {
            "description": "CTA URL",
            "type": "string"
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_announcement_bar_block",
      "description": "Create a Announcement Bar section: Sticky top banner for promotions, notices, or countdown timers.",
      "parameters": {
        "type": "object",
        "properties": {
          "message": {
            "description": "Bar text, e.g. \"Free shipping over 500 SEK\"",
            "type": "string"
          },
          "linkText": {
            "description": "Inline link label",
            "type": "string"
          },
          "linkUrl": {
            "description": "Inline link URL — the link only renders when both linkText and linkUrl are set",
            "type": "string"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "solid",
              "gradient",
              "minimal"
            ]
          },
          "backgroundColor": {
            "description": "Background color override (CSS color)",
            "type": "string"
          },
          "textColor": {
            "description": "Text color override (CSS color)",
            "type": "string"
          },
          "dismissable": {
            "description": "Allow visitors to close the bar",
            "type": "boolean"
          },
          "sticky": {
            "description": "Keep the bar pinned to the top while scrolling",
            "type": "boolean"
          },
          "showCountdown": {
            "description": "Show a countdown next to the message",
            "type": "boolean"
          },
          "countdownTarget": {
            "description": "ISO date/time the countdown runs to (required when showCountdown is on)",
            "type": "string"
          }
        },
        "required": [
          "message"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_tabs_block",
      "description": "Create a Tabs section: Tabbed content sections for organized information.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "tabs": {
            "description": "Tab items",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "orientation": {
            "description": "Tab orientation",
            "type": "string",
            "enum": [
              "horizontal",
              "vertical"
            ]
          },
          "variant": {
            "description": "Tab style",
            "type": "string",
            "enum": [
              "underline",
              "pills",
              "boxed"
            ]
          },
          "defaultTab": {
            "description": "ID of default active tab",
            "type": "string"
          }
        },
        "required": [
          "tabs"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_marquee_block",
      "description": "Create a Marquee section: Scrolling text or logo ticker.",
      "parameters": {
        "type": "object",
        "properties": {
          "items": {
            "description": "Array of items [{ id, text, icon }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "speed": {
            "description": "Scroll speed",
            "type": "string",
            "enum": [
              "slow",
              "normal",
              "fast"
            ]
          },
          "direction": {
            "description": "Scroll direction",
            "type": "string",
            "enum": [
              "left",
              "right"
            ]
          },
          "pauseOnHover": {
            "description": "Pause on hover",
            "type": "boolean"
          },
          "separator": {
            "description": "Separator between items",
            "type": "string"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "gradient",
              "outlined"
            ]
          }
        },
        "required": [
          "items"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_embed_block",
      "description": "Create a Embed section: Embed external content (Vimeo, Spotify, custom iframes).",
      "parameters": {
        "type": "object",
        "properties": {
          "url": {
            "description": "URL to embed",
            "type": "string"
          },
          "provider": {
            "description": "Force a provider instead of detecting it from the URL",
            "type": "string",
            "enum": [
              "vimeo",
              "spotify",
              "soundcloud",
              "codepen",
              "figma",
              "loom",
              "custom"
            ]
          },
          "customEmbed": {
            "description": "Raw embed HTML, used instead of url — rendered as-is, so only paste code you trust",
            "type": "string"
          },
          "caption": {
            "description": "Caption under the embed",
            "type": "string"
          },
          "aspectRatio": {
            "description": "Embed aspect ratio",
            "type": "string",
            "enum": [
              "auto",
              "16:9",
              "4:3",
              "1:1",
              "9:16"
            ]
          },
          "maxWidth": {
            "description": "Embed width",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg",
              "full"
            ]
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "card",
              "minimal"
            ]
          }
        },
        "required": [
          "url"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_lottie_block",
      "description": "Create a Lottie Animation section: Lightweight vector animations with interactive playback controls.",
      "parameters": {
        "type": "object",
        "properties": {
          "src": {
            "description": "URL to Lottie JSON animation file",
            "type": "string"
          },
          "autoplay": {
            "description": "Auto-play on load",
            "type": "boolean"
          },
          "loop": {
            "description": "Loop animation",
            "type": "boolean"
          },
          "speed": {
            "description": "Playback speed (0.25-2)",
            "type": "number"
          },
          "direction": {
            "description": "Play direction",
            "type": "string",
            "enum": [
              "forward",
              "reverse"
            ]
          },
          "playOn": {
            "description": "Trigger to start playing",
            "type": "string",
            "enum": [
              "load",
              "hover",
              "click",
              "scroll"
            ]
          },
          "hoverAction": {
            "description": "Action on hover",
            "type": "string",
            "enum": [
              "play",
              "pause",
              "reverse"
            ]
          },
          "size": {
            "description": "Animation size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg",
              "xl",
              "full"
            ]
          },
          "maxWidth": {
            "description": "Custom max width in pixels",
            "type": "number"
          },
          "aspectRatio": {
            "description": "Aspect ratio",
            "type": "string",
            "enum": [
              "auto",
              "1:1",
              "16:9",
              "4:3"
            ]
          },
          "alignment": {
            "description": "Horizontal alignment",
            "type": "string",
            "enum": [
              "left",
              "center",
              "right"
            ]
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "card",
              "floating"
            ]
          },
          "backgroundColor": {
            "description": "Background color (leave empty for transparent)",
            "type": "string"
          },
          "alt": {
            "description": "Alt text for accessibility",
            "type": "string"
          },
          "caption": {
            "description": "Caption below animation",
            "type": "string"
          }
        },
        "required": [
          "src"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_table_block",
      "description": "Create a Table section: Data table with optional sticky header and hover effects.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Table title",
            "type": "string"
          },
          "caption": {
            "description": "Table caption",
            "type": "string"
          },
          "columns": {
            "description": "Column definitions [{ id, header, align }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "rows": {
            "description": "Row data [{ [columnId]: value }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Table style",
            "type": "string",
            "enum": [
              "default",
              "striped",
              "bordered",
              "minimal"
            ]
          },
          "size": {
            "description": "Cell padding",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "stickyHeader": {
            "description": "Sticky header on scroll",
            "type": "boolean"
          },
          "highlightOnHover": {
            "description": "Highlight rows on hover",
            "type": "boolean"
          }
        },
        "required": [
          "columns",
          "rows"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_countdown_block",
      "description": "Create a Countdown section: Countdown timer to a specific date.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "targetDate": {
            "description": "Target date (ISO format)",
            "type": "string"
          },
          "expiredMessage": {
            "description": "Message when countdown expires",
            "type": "string"
          },
          "showDays": {
            "description": "Show days",
            "type": "boolean"
          },
          "showHours": {
            "description": "Show hours",
            "type": "boolean"
          },
          "showMinutes": {
            "description": "Show minutes",
            "type": "boolean"
          },
          "showSeconds": {
            "description": "Show seconds",
            "type": "boolean"
          },
          "variant": {
            "description": "Display style",
            "type": "string",
            "enum": [
              "default",
              "cards",
              "minimal",
              "circular"
            ]
          },
          "size": {
            "description": "Size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "labels": {
            "description": "Unit labels, for translating the timer: { days, hours, minutes, seconds }. Any omitted key falls back to English.",
            "type": "object"
          }
        },
        "required": [
          "targetDate"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_progress_block",
      "description": "Create a Progress section: Progress bars or circular indicators.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "items": {
            "description": "Progress items [{ id, label, value, color, icon }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Display style",
            "type": "string",
            "enum": [
              "default",
              "circular",
              "minimal",
              "cards"
            ]
          },
          "size": {
            "description": "Size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "showLabels": {
            "description": "Show item labels",
            "type": "boolean"
          },
          "showPercentage": {
            "description": "Show percentage",
            "type": "boolean"
          },
          "animated": {
            "description": "Animate on scroll",
            "type": "boolean"
          },
          "animationDuration": {
            "description": "Animation length in ms",
            "type": "number"
          }
        },
        "required": [
          "items"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_badge_block",
      "description": "Create a Badge section: Collection of badges, certifications, or partner logos.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "badges": {
            "description": "Badge items [{ id, title, subtitle, icon, image, url }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Display style",
            "type": "string",
            "enum": [
              "default",
              "cards",
              "minimal",
              "bordered"
            ]
          },
          "columns": {
            "description": "Number of columns",
            "type": "number"
          },
          "size": {
            "description": "Badge size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "showTitles": {
            "description": "Show badge titles",
            "type": "boolean"
          },
          "grayscale": {
            "description": "Grayscale images",
            "type": "boolean"
          }
        },
        "required": [
          "badges"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_social_proof_block",
      "description": "Create a Social Proof section: Display social proof metrics, ratings, and live activity.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "items": {
            "description": "Social proof items [{ type, label, value, rating, activity }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Display style",
            "type": "string",
            "enum": [
              "default",
              "cards",
              "minimal",
              "banner",
              "floating"
            ]
          },
          "layout": {
            "description": "Layout",
            "type": "string",
            "enum": [
              "horizontal",
              "vertical",
              "grid"
            ]
          },
          "size": {
            "description": "Size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "columns": {
            "description": "Number of columns in the grid layout",
            "type": "number"
          },
          "animated": {
            "description": "Animate counters",
            "type": "boolean"
          },
          "animationDuration": {
            "description": "Counter animation length in ms",
            "type": "number"
          },
          "showIcons": {
            "description": "Show each item's icon",
            "type": "boolean"
          },
          "showLiveIndicator": {
            "description": "Show live indicator",
            "type": "boolean"
          },
          "liveText": {
            "description": "Label shown next to the live indicator",
            "type": "string"
          }
        },
        "required": [
          "items"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_notification_toast_block",
      "description": "Create a Notification Toast section: Animated notification popups for social proof or alerts.",
      "parameters": {
        "type": "object",
        "properties": {
          "notifications": {
            "description": "Notification items [{ type, icon, title, message, image, timestamp, location }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Display style",
            "type": "string",
            "enum": [
              "default",
              "minimal",
              "card",
              "bubble"
            ]
          },
          "position": {
            "description": "Screen position",
            "type": "string",
            "enum": [
              "bottom-left",
              "bottom-right",
              "top-left",
              "top-right"
            ]
          },
          "displayDuration": {
            "description": "How long each notification stays on screen, in seconds",
            "type": "number"
          },
          "delayBetween": {
            "description": "Pause between notifications, in seconds",
            "type": "number"
          },
          "initialDelay": {
            "description": "Delay before the first notification, in seconds",
            "type": "number"
          },
          "maxWidth": {
            "description": "Max width",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "animationType": {
            "description": "Animation type",
            "type": "string",
            "enum": [
              "slide",
              "fade",
              "pop"
            ]
          },
          "showCloseButton": {
            "description": "Show the dismiss button; dismissing stops the whole sequence",
            "type": "boolean"
          },
          "showImage": {
            "description": "Show each notification's image (falls back to its icon)",
            "type": "boolean"
          },
          "showTimestamp": {
            "description": "Show each notification's timestamp line",
            "type": "boolean"
          },
          "loop": {
            "description": "Start over after the last notification instead of stopping",
            "type": "boolean"
          }
        },
        "required": [
          "notifications"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_floating_cta_block",
      "description": "Create a Floating CTA section: Sticky call-to-action that appears on scroll.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Headline — the CTA message. Rendered by the bar, card and minimal variants; the pill variant shows only the button.",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting line under the title. Rendered by the bar and card variants only.",
            "type": "string"
          },
          "buttonText": {
            "description": "Button label",
            "type": "string"
          },
          "buttonUrl": {
            "description": "Button URL",
            "type": "string"
          },
          "secondaryButtonText": {
            "description": "Optional second button label; renders only together with secondaryButtonUrl (bar and card variants)",
            "type": "string"
          },
          "secondaryButtonUrl": {
            "description": "Optional second button URL; renders only together with secondaryButtonText",
            "type": "string"
          },
          "showAfterScroll": {
            "description": "Reveal once this PERCENTAGE of the page has been scrolled, 0-100 (not pixels)",
            "type": "number"
          },
          "hideOnScrollUp": {
            "description": "Hide again while the visitor scrolls back up",
            "type": "boolean"
          },
          "variant": {
            "description": "Display style. \"pill\" is button-only — do not put copy in title for it",
            "type": "string",
            "enum": [
              "bar",
              "card",
              "minimal",
              "pill"
            ]
          },
          "position": {
            "description": "Screen position; ignored by the \"bar\" variant, which always spans the bottom",
            "type": "string",
            "enum": [
              "bottom",
              "bottom-left",
              "bottom-right"
            ]
          },
          "size": {
            "description": "Size",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "showCloseButton": {
            "description": "Show the dismiss (X) control",
            "type": "boolean"
          },
          "closePersistent": {
            "description": "Remember the dismissal for the rest of the session",
            "type": "boolean"
          },
          "showScrollTop": {
            "description": "Add a back-to-top button beside the CTA (pill variant only)",
            "type": "boolean"
          },
          "animationType": {
            "description": "Entrance animation",
            "type": "string",
            "enum": [
              "slide",
              "fade",
              "scale"
            ]
          }
        },
        "required": [
          "title",
          "buttonText",
          "buttonUrl"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_webinar_block",
      "description": "Create a Webinar section: Display upcoming and past webinars with registration and recording links.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "description": {
            "description": "Section description",
            "type": "string"
          },
          "maxItems": {
            "description": "Max webinars to show",
            "type": "number"
          },
          "showPast": {
            "description": "Show past webinars with recordings",
            "type": "boolean"
          },
          "variant": {
            "description": "Display style",
            "type": "string",
            "enum": [
              "default",
              "card",
              "minimal"
            ]
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_bento_grid_block",
      "description": "Create a Bento Grid section: Responsive masonry-style card grid with variable-span items. Great for showcasing features, services, or highlights with a visually varied layout.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "eyebrow": {
            "description": "Small label displayed above the title",
            "type": "string"
          },
          "eyebrowColor": {
            "description": "Eyebrow color as a CSS/hex value; defaults to brand primary",
            "type": "string"
          },
          "items": {
            "description": "Grid items [{ id, title, description?, icon?, span?, accentColor?, linkUrl?, linkLabel? }]. span: \"normal\" | \"wide\" | \"tall\" | \"large\"",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "columns": {
            "description": "Number of columns (3 or 4)",
            "type": "number"
          },
          "gap": {
            "description": "Gap between items",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "default",
              "glass",
              "bordered"
            ]
          },
          "staggeredReveal": {
            "description": "Animate the cards in one by one as they enter the viewport",
            "type": "boolean"
          }
        },
        "required": [
          "items"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_parallax_section_block",
      "description": "Create a Parallax Section section: Full-bleed section with a background image and slow-parallax scroll effect. Great for storytelling breakers between content sections.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Headline overlaid on the image",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text under the headline",
            "type": "string"
          },
          "backgroundImage": {
            "description": "Background image URL",
            "type": "string"
          },
          "height": {
            "description": "Section height",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg",
              "xl"
            ]
          },
          "textColor": {
            "description": "Text color scheme",
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "overlayOpacity": {
            "description": "Overlay opacity 0-100",
            "type": "number"
          },
          "contentAlignment": {
            "description": "Content alignment",
            "type": "string",
            "enum": [
              "left",
              "center",
              "right"
            ]
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_section_divider_block",
      "description": "Create a Section Divider section: Decorative shape transition between two sections (wave, diagonal, curved, zigzag, triangle).",
      "parameters": {
        "type": "object",
        "properties": {
          "shape": {
            "description": "Divider shape",
            "type": "string",
            "enum": [
              "wave",
              "diagonal",
              "curved",
              "zigzag",
              "triangle"
            ]
          },
          "color": {
            "description": "Foreground color (CSS color)",
            "type": "string"
          },
          "bgColor": {
            "description": "Background color (CSS color)",
            "type": "string"
          },
          "height": {
            "description": "Divider height",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg"
            ]
          },
          "flip": {
            "description": "Flip vertically",
            "type": "boolean"
          },
          "invert": {
            "description": "Invert colors",
            "type": "boolean"
          }
        },
        "required": [
          "shape"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_featured_carousel_block",
      "description": "Create a Featured Carousel section: Full-bleed image slideshow with title/description/CTA per slide. Ideal for hero rotations, campaigns, or featured collections.",
      "parameters": {
        "type": "object",
        "properties": {
          "slides": {
            "description": "Slides [{ id, title, subtitle?, description?, image, ctaLabel?, ctaUrl?, ctaVariant?, textPosition?, overlayOpacity? }]",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "autoPlay": {
            "description": "Auto-advance slides",
            "type": "boolean"
          },
          "interval": {
            "description": "Milliseconds per slide",
            "type": "number"
          },
          "height": {
            "description": "Carousel height",
            "type": "string",
            "enum": [
              "sm",
              "md",
              "lg",
              "full"
            ]
          },
          "showArrows": {
            "description": "Show prev/next arrows",
            "type": "boolean"
          },
          "showDots": {
            "description": "Show pagination dots",
            "type": "boolean"
          },
          "pauseOnHover": {
            "description": "Pause auto-play on hover",
            "type": "boolean"
          },
          "transition": {
            "description": "Transition style",
            "type": "string",
            "enum": [
              "fade",
              "slide"
            ]
          }
        },
        "required": [
          "slides"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_sticky_scroll_block",
      "description": "Create a Sticky Scroll Story section: Two-column narrative layout: chapters scroll on one side while a sticky visual pins on the other. Great for product tours, case studies, and step-by-step storytelling.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "eyebrow": {
            "description": "Small label above the title",
            "type": "string"
          },
          "visualSide": {
            "description": "Which side pins the sticky visual",
            "type": "string",
            "enum": [
              "left",
              "right"
            ]
          },
          "chapters": {
            "description": "Chapters [{ id, title, body, eyebrow?, image?, videoUrl? }] — each chapter scrolls a new visual into the sticky pane",
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "chapters"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_ai_faq_block",
      "description": "Create a AI FAQ section: FAQ list with a semantic search box and an \"Ask AI\" button that answers via the assistant using site knowledge. Use for support hubs and product help pages.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "eyebrow": {
            "description": "Small label above the title",
            "type": "string"
          },
          "items": {
            "description": "FAQ items [{ id, question, answer }] — answer is plain text/markdown",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "searchPlaceholder": {
            "description": "Search/ask input placeholder",
            "type": "string"
          },
          "askAiLabel": {
            "description": "Ask AI button label",
            "type": "string"
          },
          "emptyStateText": {
            "description": "Text shown when no FAQ matches — invites the user to ask the AI",
            "type": "string"
          }
        },
        "required": [
          "items"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_pricing_calculator_block",
      "description": "Create a Pricing Calculator section: Interactive card with sliders that compute a live total based on variables (users, projects, storage, etc.). Use to give visitors an instant price estimate.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Calculator title",
            "type": "string"
          },
          "subtitle": {
            "description": "Calculator subtitle",
            "type": "string"
          },
          "eyebrow": {
            "description": "Small label above the title",
            "type": "string"
          },
          "basePrice": {
            "description": "Fixed base price added to the variable total",
            "type": "number"
          },
          "currencySymbol": {
            "description": "Currency symbol prefix",
            "type": "string"
          },
          "billingLabel": {
            "description": "Suffix after the total (e.g. \"per month\")",
            "type": "string"
          },
          "variables": {
            "description": "Sliders [{ id, label, unit, min, max, step, unitPrice, defaultValue }] — total = basePrice + Σ(value × unitPrice)",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "primaryButton": {
            "description": "CTA button { text, url }",
            "type": "object"
          },
          "secondaryNote": {
            "description": "Small print under the total",
            "type": "string"
          }
        },
        "required": [
          "variables"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_quick_links_block",
      "description": "Create a Quick Links section: Prominent row of primary/secondary link buttons under a heading. Use for navigation hubs, \"how can we help\" bars, or top-of-page tasks.",
      "parameters": {
        "type": "object",
        "properties": {
          "heading": {
            "description": "Heading shown next to the links",
            "type": "string"
          },
          "links": {
            "description": "Links [{ id, label, url, variant?, icon? }] — variant: \"primary\" | \"secondary\"",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "variant": {
            "description": "Background variant",
            "type": "string",
            "enum": [
              "dark",
              "primary",
              "muted"
            ]
          },
          "layout": {
            "description": "Layout style",
            "type": "string",
            "enum": [
              "centered",
              "split"
            ]
          }
        },
        "required": [
          "links"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_chat_launcher_block",
      "description": "Create a Chat Launcher section: Chat input surface that opens the site AI assistant when the visitor submits a message. Use as an inline \"ask us anything\" section — NOT the floating widget.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Title above the input",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text",
            "type": "string"
          },
          "placeholder": {
            "description": "Input placeholder",
            "type": "string"
          },
          "showQuickActions": {
            "description": "Show suggested prompt chips",
            "type": "boolean"
          },
          "quickActionCount": {
            "description": "How many suggestions",
            "type": "number"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "minimal",
              "card",
              "hero-integrated"
            ]
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_ai_assistant_block",
      "description": "Create a AI Assistant section: Hero-scale AI assistant surface — a prominent search-style input with optional background image, badge, and suggested prompts. Use as the primary intent-capture section on landing pages.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Headline above the input",
            "type": "string"
          },
          "subtitle": {
            "description": "Supporting text",
            "type": "string"
          },
          "placeholder": {
            "description": "Input placeholder",
            "type": "string"
          },
          "variant": {
            "description": "Visual style",
            "type": "string",
            "enum": [
              "hero",
              "card",
              "minimal",
              "split"
            ]
          },
          "backgroundImage": {
            "description": "Background image URL (hero variant)",
            "type": "string"
          },
          "overlayOpacity": {
            "description": "Overlay opacity 0-100",
            "type": "number"
          },
          "suggestedPrompts": {
            "description": "Array of prompt strings shown as suggestion chips",
            "type": "array",
            "items": {
              "type": "object"
            }
          },
          "showBadge": {
            "description": "Show badge (e.g. \"AI-powered\")",
            "type": "boolean"
          },
          "badgeText": {
            "description": "Badge label",
            "type": "string"
          },
          "iconStyle": {
            "description": "Input icon",
            "type": "string",
            "enum": [
              "sparkles",
              "shopping",
              "search"
            ]
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_terms_block",
      "description": "Create a Contract Terms section: Published contract terms (Allmänna villkor, Tjänstevillkor) as an expandable list with per-document PDF copies. Sourced from contract templates marked public — place on any page to give agreements a stable terms URL. Set Terms page slug in Site Settings to the page holding this block.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "subtitle": {
            "description": "Section subtitle",
            "type": "string"
          },
          "showPrint": {
            "description": "Offer a print/PDF copy per document",
            "type": "boolean"
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_contact_block",
      "description": "Create a Contact section: Contact section with heading and a contact form or contact-info card. Use as a page-level contact section.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "description": "Section title",
            "type": "string"
          },
          "showForm": {
            "description": "Render the contact form alongside the details",
            "type": "boolean"
          },
          "phone": {
            "description": "Phone number; rendered as a tel: link",
            "type": "string"
          },
          "email": {
            "description": "Email address; rendered as a mailto: link",
            "type": "string"
          },
          "address": {
            "description": "Postal address; line breaks are preserved",
            "type": "string"
          },
          "hours": {
            "description": "Opening hours rows",
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        }
      }
    }
  }
] as const;

/** Map tool call name back to block type */
export function toolNameToBlockType(toolName: string): string | null {
  if (!toolName.startsWith('create_') || !toolName.endsWith('_block')) return null;
  return toolName.slice(7, -6).replace(/_/g, '-');
}
