#!/usr/bin/env bun
/**
 * Seed Export Script
 *
 * Exports the three things an instance needs but cannot get from migrations,
 * as versioned artifacts under supabase/seed/:
 *   module-skills.json       every module's skillSeeds (+ platform seeds)
 *   module-automations.json  every module's automation seeds
 *   locale-packs.json        each accounting pack's chart of accounts
 *
 * This decouples the database sync (scripts/sync-skills.ts) from the frontend
 * module graph — the sync tool reads the JSON, never imports React code, and
 * works against any Supabase/Postgres instance.
 *
 * Automations and the chart were previously reachable ONLY from React:
 * automations from bootstrapModule(), the chart from topUpLocalePackSeeds().
 * An install where nobody opened the admin got neither — and FlowWink is sold
 * as agent-operated, so "nobody logs in" is a supported case, not an edge one.
 * Both cost us real bugs on 2026-07-20/21 (a fleet deploy that silently seeded
 * no automations, and a fresh install running on five accounts while the
 * bookkeeping RPCs posted to 1930).
 *
 * Run whenever module seeds or a locale pack change (same idea as
 * scripts/templates-to-json.ts for templates):
 *   bun run scripts/skills-to-json.ts
 */
import { resolve, join } from 'node:path';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';

// Module definitions transitively import browser-only helpers (e.g. locale-packs
// read localStorage at import time). Shim them so the graph loads under Bun.
const noopStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {}, clear: () => {}, key: () => null, length: 0 };
(globalThis as any).localStorage ??= noopStorage;
(globalThis as any).window ??= { localStorage: noopStorage, matchMedia: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) };

const ROOT = resolve(import.meta.dir, '..');
const OUT_DIR = join(ROOT, 'supabase', 'seed');

interface ModuleLike { id?: string; skillSeeds?: unknown[]; automations?: unknown[] }

const modules = await import(join(ROOT, 'src', 'lib', 'modules', 'index.ts')) as Record<string, unknown>;

const out: Array<{ moduleId: string; skills: unknown[] }> = [];
const autos: Array<{ moduleId: string; automations: unknown[] }> = [];
let total = 0;
let autoTotal = 0;
for (const exported of Object.values(modules)) {
  const m = exported as ModuleLike;
  if (!m || typeof m !== 'object' || !m.id) continue;
  if (Array.isArray(m.skillSeeds) && m.skillSeeds.length > 0) {
    out.push({ moduleId: m.id, skills: m.skillSeeds });
    total += m.skillSeeds.length;
  }
  if (Array.isArray(m.automations) && m.automations.length > 0) {
    autos.push({ moduleId: m.id, automations: m.automations });
    autoTotal += m.automations.length;
  }
}

// Platform-level skills (src/lib/platform-seeds.ts) are not owned by any module —
// they must exist on every instance regardless of module toggles. Emit them as
// the pseudo-module `platform` so sync-skills / fleet drift detection cover them
// (previously they were invisible to the CLI sync path — a drift hole).
const platformSeeds = await import(join(ROOT, 'src', 'lib', 'platform-seeds.ts')) as { PLATFORM_SKILLS?: unknown[]; PLATFORM_AUTOMATIONS?: unknown[] };
if (Array.isArray(platformSeeds.PLATFORM_SKILLS) && platformSeeds.PLATFORM_SKILLS.length > 0) {
  out.push({ moduleId: 'platform', skills: platformSeeds.PLATFORM_SKILLS });
  total += platformSeeds.PLATFORM_SKILLS.length;
}
// Platform AUTOMATIONS travel the same way — before this they were reachable
// only via bootstrapModule() in the browser, the exact class of gap this
// artifact exists to close (found 2026-07-22 when Integration Health Check
// never reached the fleet through sync-skills).
if (Array.isArray(platformSeeds.PLATFORM_AUTOMATIONS) && platformSeeds.PLATFORM_AUTOMATIONS.length > 0) {
  autos.push({ moduleId: 'platform', automations: platformSeeds.PLATFORM_AUTOMATIONS });
  autoTotal += platformSeeds.PLATFORM_AUTOMATIONS.length;
}
out.sort((a, b) => a.moduleId.localeCompare(b.moduleId));

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
const artifact = {
  _comment: 'Generated by scripts/skills-to-json.ts — DO NOT edit by hand. Run sync-skills.ts to apply to an instance.',
  generated_at: new Date().toISOString(),
  module_count: out.length,
  skill_count: total,
  modules: out,
};
writeFileSync(join(OUT_DIR, 'module-skills.json'), JSON.stringify(artifact, null, 2) + '\n');
console.log(`✅ Wrote supabase/seed/module-skills.json — ${out.length} modules, ${total} skills`);

// The same skills, bundled into agent-execute — so every edge deploy CARRIES
// its skill payload and the sync_skills_from_code handler can reconcile the
// instance without a browser or DATABASE_URL (the 4th deploy layer follows the
// other three). Deliberately no generated_at: the file must be byte-identical
// for identical content, so the handler's content hash is stable across
// regenerations and "unchanged" short-circuits stay cheap.
writeFileSync(
  join(ROOT, 'supabase', 'functions', 'agent-execute', '_module-skills.json'),
  JSON.stringify({ skill_count: total, modules: out }),
);
console.log(`✅ Wrote supabase/functions/agent-execute/_module-skills.json (edge bundle)`);

// The skill → owning module map, as a _shared TypeScript module.
//
// agent-execute authorizes non-admin callers per the skill's OWNING module
// (can_access_module — the one dial, #102). Any surface that OFFERS a skill
// needs the same map, or it offers what execution will refuse: FlowWork staged
// three operations that were guaranteed to 403, and three humans clicked
// approve on them (QA, 2026-08-20). Discovery and execution must read the same
// ownership.
//
// Emitted as .ts under _shared/ (not JSON next to one function) because
// _shared is what every edge function can import — the map is a platform fact,
// not agent-execute's private one.
const ownerLines = out
  .flatMap((m) => (m.skills as Array<{ name?: string }>).map((s) => [String(s.name), m.moduleId] as const))
  .filter(([name]) => name && name !== 'undefined')
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([name, moduleId]) => `  ${JSON.stringify(name)}: ${JSON.stringify(moduleId)},`);
writeFileSync(
  join(ROOT, 'supabase', 'functions', '_shared', 'skills', 'skill-modules.ts'),
  `/**
 * GENERATED by scripts/skills-to-json.ts — DO NOT EDIT BY HAND.
 * Run \`npm run skills:json\` after changing any module's skillSeeds.
 *
 * Skill name → owning module id (the same ownership agent-execute builds from
 * _module-skills.json to authorize non-admin callers via can_access_module).
 * Skills absent from this map, and skills owned by the \`platform\`
 * pseudo-module, are admin-only — fail closed, exactly as the executor does.
 */
export const SKILL_OWNER_MODULE: Readonly<Record<string, string>> = Object.freeze({
${ownerLines.join('\n')}
});

/** Owning module id, or null when the skill is unmapped (⇒ admin-only). */
export function ownerModuleOf(skillName: string): string | null {
  return SKILL_OWNER_MODULE[skillName] ?? null;
}
`,
);
console.log(`  ✅ supabase/functions/_shared/skills/skill-modules.ts (${ownerLines.length} skills)`);

// ── Automations ─────────────────────────────────────────────────────────────
autos.sort((a, b) => a.moduleId.localeCompare(b.moduleId));
writeFileSync(
  join(OUT_DIR, 'module-automations.json'),
  JSON.stringify(
    {
      _comment:
        'Generated by scripts/skills-to-json.ts — DO NOT edit by hand. Applied by sync-skills.ts, which inserts by name only (never updates), so an operator-edited schedule survives a sync.',
      generated_at: new Date().toISOString(),
      module_count: autos.length,
      automation_count: autoTotal,
      modules: autos,
    },
    null,
    2,
  ) + '\n',
);
console.log(`✅ Wrote supabase/seed/module-automations.json — ${autos.length} modules, ${autoTotal} automations`);

// ── Locale packs (chart of accounts + bookkeeping templates) ────────────────
// Chart and TEMPLATES travel — both are data. (An earlier version claimed
// templates were code and left them behind; liteit ran the proof week on 15 of
// the pack's 98 templates because the browser top-up had aborted and no other
// path carried them.) Adapters and year-end proposals are functions and stay
// in code.
const lp = (await import(join(ROOT, 'src', 'lib', 'locale-packs', 'index.ts'))) as {
  LOCALE_PACKS?: Record<string, { id: string; label?: string; chart?: unknown[]; templates?: unknown[]; countries?: string[] }>;
  DEFAULT_LOCALE_ID?: string;
};
const packs = Object.values(lp.LOCALE_PACKS ?? {})
  .filter((p) => Array.isArray(p.chart) && p.chart.length > 0)
  .map((p) => ({
    id: p.id,
    label: p.label ?? p.id,
    // The Odoo key: which business countries this pack serves ('*' = the
    // generic fallback, our l10n_generic_coa). Lets server-side consumers
    // resolve country → pack without importing the frontend registry.
    countries: (p as { countries?: string[] }).countries ?? [],
    accounts: p.chart as unknown[],
    templates: (p as { templates?: unknown[] }).templates ?? [],
  }))
  .sort((a, b) => a.id.localeCompare(b.id));
writeFileSync(
  join(OUT_DIR, 'locale-packs.json'),
  JSON.stringify(
    {
      _comment:
        'Generated by scripts/skills-to-json.ts — DO NOT edit by hand. sync-skills.ts inserts missing account codes for the instance\'s active pack, mirroring topUpLocalePackSeeds().',
      generated_at: new Date().toISOString(),
      default_pack: lp.DEFAULT_LOCALE_ID ?? null,
      packs,
    },
    null,
    2,
  ) + '\n',
);
console.log(
  `✅ Wrote supabase/seed/locale-packs.json — ${packs.length} pack(s), ${packs.reduce((n, p) => n + p.accounts.length, 0)} accounts, ${packs.reduce((n, p) => n + ((p as any).templates?.length ?? 0), 0)} templates`,
);

// Same artifact, bundled into agent-execute (the way _templates.json is) so
// install_template can activate a template's accounting locale and seed its
// chart without a browser session. Edge deploys only bundle the function's own
// directory, so supabase/seed/ is out of reach there.
const edgeCopy = join(ROOT, 'supabase', 'functions', 'agent-execute', '_locale-packs.json');
writeFileSync(
  edgeCopy,
  JSON.stringify({ default_pack: lp.DEFAULT_LOCALE_ID ?? null, packs }) + '\n',
);
console.log(`  ✅ supabase/functions/agent-execute/_locale-packs.json`);

// The visitor-text catalogue (src/data/ui-text-catalog.json, every t('key',
// 'English') call site) travels the same way, so translate_ui_text can fill a
// language's overlay for keys the site has never customised.
const uiTextCatalog = join(ROOT, 'src', 'data', 'ui-text-catalog.json');
const uiTextEdgeCopy = join(ROOT, 'supabase', 'functions', 'agent-execute', '_ui-text-catalog.json');
writeFileSync(uiTextEdgeCopy, readFileSync(uiTextCatalog, 'utf8'));
console.log(`  ✅ supabase/functions/agent-execute/_ui-text-catalog.json`);
