// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { noteAuthResponse } from '@/lib/auth-diagnostics';

// Outside a browser (Bun/Node build scripts — skills:json, templates:json,
// sync-skills — import the module tree, and the tree imports this client) an
// unset URL must not abort the whole script: createClient throws on an empty
// URL. Fall back to an obviously-unusable placeholder there. In the browser
// nothing changes — main.tsx still gates on isSupabaseConfigured() before
// importing the app, so a misconfigured deploy gets its legible error page,
// and a repo never needs a committed .env pointing at somebody's instance.
const IN_BROWSER = typeof window !== 'undefined' && typeof document !== 'undefined';
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || (IN_BROWSER ? '' : 'https://unconfigured.invalid');
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (IN_BROWSER ? '' : 'unconfigured');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: async (input, init) => {
      const headers = new Headers(init?.headers);
      const visitorChatSessionId = localStorage.getItem('chat-session-id');

      // x-chat-session is only consumed by PostgREST/RLS on chat tables.
      // Do NOT inject it into /functions/v1/ calls — edge functions don't
      // read it and most don't allow it in CORS, causing preflight failures.
      const url = typeof input === 'string'
        ? input
        : input instanceof URL
          ? input.href
          : (input as Request).url;
      const isFunctionCall = url.includes('/functions/v1/');

      if (visitorChatSessionId && !isFunctionCall && !headers.has('x-chat-session')) {
        headers.set('x-chat-session', visitorChatSessionId);
      }

      // Auth failures are recorded (metadata only) so a dropped session can
      // be explained on the sign-in page instead of reported as "sometimes
      // errors". See src/lib/auth-diagnostics.ts.
      const res = await fetch(input, { ...init, headers });
      if (!res.ok) void noteAuthResponse(url, res);
      return res;
    },
  },

  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});